//! `cluman` library crate — shared schemas, client executor trait, and
//! controller entry-point.
//!
//! # Public surface
//!
//! | Item | Purpose |
//! |---|---|
//! | [`PORT`] | Default port every `cluman` service listens on. |
//! | [`schemas`] | All wire-format types (`Task`, `ServerState`, `Mode`, …). |
//! | [`Executor`] | Trait for running a Docker Compose file; mockable in tests. |
//! | [`ProcessExecutor`] | Production [`Executor`] that shells out to `docker compose`. |
//! | [`run_client_with`] | Client entry-point parameterised over an [`Executor`]. |
//! | [`controller`] | Controller module — [`controller::ControllerArgs`] and [`controller::run_controller`]. |
//!
//! Splitting the executor out from the client startup logic means integration
//! tests can inject a `MockExecutor` (generated by `mockall` under `#[cfg(test)]`)
//! or a hand-written spy without requiring Docker to be present on the test host.

/// Default TCP port every `cluman` service (client, server) listens on.
///
/// Defined in the library crate so that both the binary (`main.rs`) and
/// integration tests can reference it without duplication.
pub const PORT: u16 = 9999;

// ── Schemas ───────────────────────────────────────────────────────────────────

pub mod schemas;

// ── Client ────────────────────────────────────────────────────────────────────
//
// `pub mod client` is necessary for integration tests to import:
//
//   use cluman::Executor;            // the compose-execution trait
//   use cluman::ProcessExecutor;     // production impl
//   use cluman::run_client_with;     // entry-point parameterised over Executor
//
// The flat re-exports below save callers from writing `cluman::client::Foo`.

pub mod client;

pub use client::Executor;
pub use client::ProcessExecutor;
pub use client::run_client_with;

// ── Controller ────────────────────────────────────────────────────────────────
//
// Exposed as `pub mod` so that integration tests can import:
//
//   use cluman::controller::ControllerArgs;
//   use cluman::controller::run_controller;

pub mod controller;
