FROM docker.io/library/debian:stable-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
        make perl python3 flex bison bc \
        libssl-dev libelf-dev \
        pahole sbsigntool \
        ccache \
    && rm -rf /var/lib/apt/lists/*
